server:
  port: 8764
spring:
  application:
    name: kgc-springcloud-service
  redis:
    host: localhost
    port: 6379
    password:
  datasource:
    url: jdbc:mysql://localhost:3306/wy?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/