server:
  port: 8764
spring:
  application:
    name: kgc-springcloud-service
  redis:
    host: localhost
    port: 6379
    password:
  datasource:
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  mail:
    host: smtp.163.com
    username: jt_java@163.com
    password: zhuce123456
    default-encoding: utf-8
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/