server:
  port: 9001
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/billogg/2019-10-29-test.git
          search-paths: test
          username: jt_java@163.com
          password: zhuce&123456
          force-pull: true
      label: master